#!/bin/sh -e

hostname="$(cat "${__global}/explorer/hostname")"

for host_manifest in \
    "${__manifest}/host_${__target_host}" \
    "${__manifest}/host_${hostname}"
do
    ! test -f "${host_manifest}" && continue
    . "${host_manifest}"
    exit
done

for host_type in \
    "__host_${__target_host}" \
    "__host_${hostname}"
do
    ! command -v "${host_type}" >/dev/null && continue
    "${host_type}"
    exit
done
