#!/bin/sh

printf '%s: %s\n' \
	__target_host "${__target_host-}" \
	__target_hostname "${__target_hostname-}" \
	__target_fqdn "${__target_fqdn-}" \
	__explorer "${__explorer-}" \
	__target_host_tags "${__target_host_tags-}" \
	__cdist_log_level "${__cdist_log_level-}" \
	__cdist_log_level_name "${__cdist_log_level_name-}"
